// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package storemock

import (
	"github.com/yama6a/bolan-compare/internal/pkg/model"
	"github.com/yama6a/bolan-compare/internal/pkg/store"
	"sync"
)

// Ensure, that StoreMock does implement store.Store.
// If this is not the case, regenerate this file with moq.
var _ store.Store = &StoreMock{}

// StoreMock is a mock implementation of store.Store.
//
//	func TestSomethingThatUsesStore(t *testing.T) {
//
//		// make and configure a mocked store.Store
//		mockedStore := &StoreMock{
//			GetInterestSetsFunc: func() ([]model.InterestSet, error) {
//				panic("mock out the GetInterestSets method")
//			},
//			UpsertInterestSetFunc: func(set model.InterestSet) error {
//				panic("mock out the UpsertInterestSet method")
//			},
//		}
//
//		// use mockedStore in code that requires store.Store
//		// and then make assertions.
//
//	}
type StoreMock struct {
	// GetInterestSetsFunc mocks the GetInterestSets method.
	GetInterestSetsFunc func() ([]model.InterestSet, error)

	// UpsertInterestSetFunc mocks the UpsertInterestSet method.
	UpsertInterestSetFunc func(set model.InterestSet) error

	// calls tracks calls to the methods.
	calls struct {
		// GetInterestSets holds details about calls to the GetInterestSets method.
		GetInterestSets []struct {
		}
		// UpsertInterestSet holds details about calls to the UpsertInterestSet method.
		UpsertInterestSet []struct {
			// Set is the set argument value.
			Set model.InterestSet
		}
	}
	lockGetInterestSets   sync.RWMutex
	lockUpsertInterestSet sync.RWMutex
}

// GetInterestSets calls GetInterestSetsFunc.
func (mock *StoreMock) GetInterestSets() ([]model.InterestSet, error) {
	if mock.GetInterestSetsFunc == nil {
		panic("StoreMock.GetInterestSetsFunc: method is nil but Store.GetInterestSets was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetInterestSets.Lock()
	mock.calls.GetInterestSets = append(mock.calls.GetInterestSets, callInfo)
	mock.lockGetInterestSets.Unlock()
	return mock.GetInterestSetsFunc()
}

// GetInterestSetsCalls gets all the calls that were made to GetInterestSets.
// Check the length with:
//
//	len(mockedStore.GetInterestSetsCalls())
func (mock *StoreMock) GetInterestSetsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetInterestSets.RLock()
	calls = mock.calls.GetInterestSets
	mock.lockGetInterestSets.RUnlock()
	return calls
}

// UpsertInterestSet calls UpsertInterestSetFunc.
func (mock *StoreMock) UpsertInterestSet(set model.InterestSet) error {
	if mock.UpsertInterestSetFunc == nil {
		panic("StoreMock.UpsertInterestSetFunc: method is nil but Store.UpsertInterestSet was just called")
	}
	callInfo := struct {
		Set model.InterestSet
	}{
		Set: set,
	}
	mock.lockUpsertInterestSet.Lock()
	mock.calls.UpsertInterestSet = append(mock.calls.UpsertInterestSet, callInfo)
	mock.lockUpsertInterestSet.Unlock()
	return mock.UpsertInterestSetFunc(set)
}

// UpsertInterestSetCalls gets all the calls that were made to UpsertInterestSet.
// Check the length with:
//
//	len(mockedStore.UpsertInterestSetCalls())
func (mock *StoreMock) UpsertInterestSetCalls() []struct {
	Set model.InterestSet
} {
	var calls []struct {
		Set model.InterestSet
	}
	mock.lockUpsertInterestSet.RLock()
	calls = mock.calls.UpsertInterestSet
	mock.lockUpsertInterestSet.RUnlock()
	return calls
}
