// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package httpmock

import (
	"github.com/yama6a/bolan-compare/internal/pkg/http"
	"sync"
)

// Ensure, that ClientMock does implement http.Client.
// If this is not the case, regenerate this file with moq.
var _ http.Client = &ClientMock{}

// ClientMock is a mock implementation of http.Client.
//
//	func TestSomethingThatUsesClient(t *testing.T) {
//
//		// make and configure a mocked http.Client
//		mockedClient := &ClientMock{
//			FetchFunc: func(url string, headers map[string]string) (string, error) {
//				panic("mock out the Fetch method")
//			},
//		}
//
//		// use mockedClient in code that requires http.Client
//		// and then make assertions.
//
//	}
type ClientMock struct {
	// FetchFunc mocks the Fetch method.
	FetchFunc func(url string, headers map[string]string) (string, error)

	// calls tracks calls to the methods.
	calls struct {
		// Fetch holds details about calls to the Fetch method.
		Fetch []struct {
			// URL is the url argument value.
			URL string
			// Headers is the headers argument value.
			Headers map[string]string
		}
	}
	lockFetch sync.RWMutex
}

// Fetch calls FetchFunc.
func (mock *ClientMock) Fetch(url string, headers map[string]string) (string, error) {
	if mock.FetchFunc == nil {
		panic("ClientMock.FetchFunc: method is nil but Client.Fetch was just called")
	}
	callInfo := struct {
		URL     string
		Headers map[string]string
	}{
		URL:     url,
		Headers: headers,
	}
	mock.lockFetch.Lock()
	mock.calls.Fetch = append(mock.calls.Fetch, callInfo)
	mock.lockFetch.Unlock()
	return mock.FetchFunc(url, headers)
}

// FetchCalls gets all the calls that were made to Fetch.
// Check the length with:
//
//	len(mockedClient.FetchCalls())
func (mock *ClientMock) FetchCalls() []struct {
	URL     string
	Headers map[string]string
} {
	var calls []struct {
		URL     string
		Headers map[string]string
	}
	mock.lockFetch.RLock()
	calls = mock.calls.Fetch
	mock.lockFetch.RUnlock()
	return calls
}
